# Generated by Django 2.0.4 on 2018-07-09 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('target', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/%m/')),
                ('permanent_url', models.CharField(blank=True, max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('mode', models.IntegerField(default=301)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.CharField(max_length=100)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='links.ShortURL')),
            ],
        ),
    ]
