# Generated by Django 2.0.4 on 2018-07-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='count',
        ),
    ]
